### ISSUE TITLE
Document fails to metion that this doesn't work from sub-workflows dispatched via workflow_call

### ISSUE THREAD

**Issue by Alan-Jowett** [MicrosoftDocs/azure-dev-docs#1243]
This webpage is missing a relevant and important detail:
The sample code works fine from a top-level workflow, but if it's called from a child workflow (via the uses clause) then it fails to login with no information on why.

Example:
CI/CD.yml
```yaml
    uses: ./.github/workflows/Build.yml
    with:
      platform: ${{ matrix.platform }}
      configuration: ${{ matrix.configuration }}
      option: ${{ matrix.option }}
```
Build.yml
```yaml
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

This pattern is fairly common as it makes it easier to maintain workflows, so having this silently break will cause developers to waste hours of time until they try it from the top-level workflow.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 081be8c9-7871-db69-977c-9304daa6c870
* Version Independent ID: aa3e5074-a630-3756-be86-295d1a2d101f
* Content: [Connect GitHub and Azure](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux)
* Content Source: [articles/github/connect-from-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/connect-from-azure.md)
* Service: **azure**
* GitHub Login: @MoChilia
* Microsoft Alias: **shiyingchen**
