### ISSUE TITLE
Broken link to ConfigureRemotingForAnsible.ps1

### ISSUE THREAD

**Issue by Realiserad** [MicrosoftDocs/azure-dev-docs#1318]
When running the WinRM task in Ansible I get the following:

> Failed to download all specified files. Exiting. Error Message: CustomScript failed to download the blob https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 because it does not exist.

The URL above returns 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb5f4824-c6e0-5b17-d79b-93395ff4452d
* Version Independent ID: 7da82adc-2656-daef-c2b5-e871a932e2da
* Content: [Create a Windows virtual machine in Azure using Ansible](https://learn.microsoft.com/en-us/azure/developer/ansible/vm-configure-windows?tabs=ansible)
* Content Source: [articles/ansible/vm-configure-windows.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/ansible/vm-configure-windows.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Realiserad** [comment]
It looks like the Ansible team has moved the PowerShell script to a new repository called `ansible-documentation`. The correct link should be: https://raw.githubusercontent.com/ansible/ansible-documentation/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

Running these two Ansible tasks with the new link works. :+1: 

```yaml
- name: Enable WinRM
    azure.azcollection.azure_rm_virtualmachineextension:
      name: winrm-extension
      resource_group: FooResourceGroup
      virtual_machine_name: "{{ vm_name }}"
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: '1.9'
      settings: >
        {
          "fileUris": [
            "https://raw.githubusercontent.com/ansible/ansible-documentation/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"
          ],
          "commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"
        }
      auto_upgrade_minor_version: true
  - name: Wait for WinRM connectivity
    ansible.builtin.wait_for:
      port: 5986
      host: "{{ azure.deployment.outputs.ipAddress.value }}"
      timeout: 180
```
