### ISSUE TITLE
Update terraform output command to write out kube_config

### ISSUE THREAD

**Issue by clssn** [MicrosoftDocs/azure-dev-docs#481]
Kubernetes config is broken when extracted with terraform according to the docs.

The command to write out the kubernetes config file needs to be changed to use the `--raw` option, [here](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks#test-the-kubernetes-cluster) like so:

`echo "$(terraform output --raw kube_config)" > ./azurek8s`

Otherwise invalid yaml is written out (`EOT` markers at the beginning and end of the output).

Example:
```
<<EOT
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: removed for privacy
    server: https://removedforprivacy.hcp.westeurope.azmk8s.io:443
  name: simk8s
contexts:
- context:
    cluster: simk8s
    user: clusterUser_simulation_simk8s
  name: simk8s
current-context: simk8s
kind: Config
preferences: {}
users:
- name: clusterUser_simulation_simk8s
  user:
    client-certificate-data: removed for privacy
    client-key-data: removed for privacy
    token: removed for privacy

EOT
```
Using terraform v0.15.0. Not sure whether the EOTs are a bug or a feature, but `--raw` appears to be the style we want to have anyway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a750d14-2f87-914e-8715-fac805c8ba3b
* Version Independent ID: f8d16dbe-e594-408c-18d8-26fc95de6c65
* Content: [Create a Kubernetes cluster with Azure Kubernetes Service (AKS) using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks)
* Content Source: [articles/terraform/create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-tf-and-aks.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**
