### ISSUE TITLE
Please clarify exponential back-off and retry when making requests 

### ISSUE THREAD

**Issue by richorama** [MicrosoftDocs/azure-dev-docs#863]
Hi, thank you for writing this article, it's vey useful.

The KeyVault documentation [recommends exponential back-off and retry](https://docs.microsoft.com/en-us/azure/key-vault/general/overview-throttling#how-to-throttle-your-app-in-response-to-service-limits
) when making requests. It's unclear to me whether this policy is implemented by default when following this example.

Would you be able to clarify how this works?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e25b58-811b-ec83-0251-7a641d4a7670
* Version Independent ID: 55deb14a-7feb-fcf3-95e7-5e947f5fb061
* Content: [Tutorial: Read a secret from Azure Key Vault in a Spring Boot application](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md)
* Service: **key-vault**
* GitHub Login: @KarlErickson
* Microsoft Alias: **edburns**

**Comment by KarlErickson** [comment]
@edburns can you comment? Thanks!

**Comment by edburns** [comment]
Hello @richorama , At the point in time when @mnriem  implemented the solution (with some operational help from me) there was no back-off. Let us use this issue to discuss options for meeting this requirement.

Hello @mnriem , can you please weigh in on the best way forward to support [back-off](https://docs.microsoft.com/en-us/azure/key-vault/general/overview-throttling#how-to-throttle-your-app-in-response-to-service-limits) with the Key Vault certificate solution?

**Comment by richorama** [comment]
Thank you!

**Comment by moarychan** [comment]
Hi @richorama , Thanks for using Spring Cloud Azure libraries!

There's a default retry strategy `ExponentialBackoff` under azure-core for each HTTP-based client, in which the max retries is 3, the base delay is 800 milliseconds, the max delay is 5 seconds.

You can change these values via Spring Cloud Azure Starter Secret properties as below:

```yml
spring:
  cloud:
    azure:
#      It's a common configuration for all HTTP-based clients.
#      retry:
#        mode: exponential
#        exponential:
#          max-retries: 4
#          base-delay: PT0.0801S
#          max-delay: PT9S
      keyvault:
        secret:
          credential:
            client-id: <your client id>
            client-secret: <your client secret>
          profile:
            tenant-id: <your tenant id>
          property-source-enabled: true
          property-sources:
            - name: key-vault-property-source-1
              endpoint: <your Azure Key Vault endpoint>
#              retry:
#                mode: exponential
#                exponential:
#                  max-retries: 4
#                  base-delay: PT0.0801S
#                  max-delay: PT9S
```
