### ISSUE TITLE
ClientSecretCredential with ServiceBus

### ISSUE THREAD

**Issue by VarshaGadekar** [MicrosoftDocs/azure-dev-docs#949]
[Enter feedback here]
The document does not give information on how ClientSecretCredential works with ServiceBus.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0936eefd-61e9-9b47-c473-b0d91723cd63
* Version Independent ID: 0936eefd-61e9-9b47-c473-b0d91723cd63
* Content: [Spring Cloud Azure reference documentation](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven)
* Content Source: [articles/java/spring-framework/spring-cloud-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/spring-cloud-azure.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **v-yonghuiye**

**Comment by fangjian0423** [comment]
hi @VarshaGadekar , 

Please refer [Authenticate with Azure Active Directory](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven#authenticate-with-azure-active-directory).

The following example shows you how to authenticate using a service principal with a client secret:

```yaml
spring.cloud.azure:
  credential:
    client-id: ${AZURE_CLIENT_ID}
    client-secret: ${AZURE_CLIENT_SECRET}
  profile:
    tenant-id: ${AZURE_TENANT_ID}
```
